import webview

webview.create_window('Bobby Bot', 'https://www.google.com/search?rlz=1C1CHBF_deDE917DE917&sxsrf=ALeKk01Wyilr1A6gepfOSzRB3zq8tPXpbQ%3A1602268727266&ei=N66AX77QD_XggwfE94Fg&q=remove+all+letters+from+string+python&oq=remove+all+letters+from+string+py&gs_lcp=CgZwc3ktYWIQARgAMgUIABDJAzIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjoECAAQRzoKCAAQyQMQFBCHAjoCCABQs60DWOW0A2DpwgNoAHADeACAAVWIAfYBkgEBM5gBAKABAaoBB2d3cy13aXrIAQjAAQE&sclient=psy-ab')
webview.start()
